### ISSUE TITLE
ocr.recText giving error 

### ISSUE THREAD

**Issue by sonydaman** [NeutrinosPlatform/cordova-plugin-mobile-ocr#37] opened 2020-08-04 19:04 UTC
## Trying with :
`this.ocr.recText(OCRSourceType.BASE64, this.imgUri)`
### Unfortunaltly getting error as follows :
`Line 1824 : ERROR TypeError: Object(...) is not a function`

The issue raised on [Ionic Document](https://forum.ionicframework.com/t/cordova-plugin-mobile-ocr/153039)
### Ionic Info :
`Ionic:

   Ionic CLI          : 5.4.16 
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 18 other plugins)

Utility:

   cordova-res (update available: 0.15.1) : 0.11.0
   native-run                             : 1.0.0

System:

   Android SDK Tools : 26.1.1 
   ios-sim           : 8.0.2
   NodeJS            : v12.16.3
   npm               : 6.14.5
   OS                : macOS Catalina
   Xcode             : Xcode 11.5 Build version 11E608c
`

**Comment by ChrisTomAlx** [comment] 2020-08-14 11:48
Duplicate of #32

**Closed as completed by ChrisTomAlx** 2020-08-14 11:48 UTC
Labels: duplicate
